### ISSUE TITLE
Repository unavailable when running a new site's docker-compose.yml

### ISSUE THREAD

**Issue by Sean12mps** [DinkumInteractive/didow#1]
@gtenaschuk 
I did a fresh clone of didow.

New project created will not run if "image" in it's docker-compose.yml is not set to:
`image: didow/wordpress:5.5.1-php7.4-apache-xdebug-unit6.0`

**Comment by gtenaschuk** [comment]
Hey Sean, i forgot to update the image name in the documentation, the correct one was what we have in the docker compose file.
Maybe you can update both to the WP latest version so can play with this :)
